services:
  dice-roller:
    image: denoland/deno:2.3.5
    container_name: dice-roller
    ports:
      - "8000:8000"
    command: deno run --allow-net --allow-env app/main.ts
    volumes:
      - ./:/app